version: '3'
services:

  transcription_local:
    image: keplerlab/kaldi-vosk-wesocket-server:0.1.1
    ports:
    - "1111:1111"
    - "1112:1112"
    volumes:
       - ./api/transcription_svc/websocket-server/:/opt/transcription_svc/websocket-server/
       #- ./api/transcription_svc/models/vosk-model-en-us-daanzu-20200905-big/:/opt/transcription_svc/vosk-model-en/model/
       - ./certificates/:/opt/transcription_svc/websocket-server/certificates/
    environment:
      - SERVER_INTERFACE=0.0.0.0
      - SERVER_PORT=1111
      - SAMPLE_RATE=44100
      - VOSK_MODEL_PATH=model


  cli:
    image: keplerlab/enhant-cli:0.1.1
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./cli/:/home/cli/
      - ./nlp_lib/:/home/nlp_lib/
      - ./docs/:/home/docs/
      - ./api/transcription_svc/:/home/api/transcription_svc/
      - ./dashboard/:/home/dashboard/
      # Exclude mount node_modules directory
      #- /usr/src/app/node_modules/
