version: '3'
services:

  transcription_local:
    build: ./api/transcription_svc/Docker/
    ports:
    - "1111:1111"
    volumes:
       - ./api/transcription_svc/:/opt/transcription_svc/
       - ./certificates/:/opt/transcription_svc/websocket-server/certificates/
    environment:
      - USE_GOOGLE_TRANSCRIPTION_SERVICE=False # Set this to True if want to use Cloud Google speech to text service
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/transcription_svc/websocket-server/project-voicebox-fa7bc2f8fa18.json # Google credential file
      - SERVER_INTERFACE=0.0.0.0
      - SERVER_PORT=1111
      - SAMPLE_RATE=44100
      - VOSK_MODEL_PATH=model


  cli:
    build: ./cli/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./cli/:/home/cli/
      - ./nlp_lib/:/home/nlp_lib/
      - ./message_processor/:/home/message_processor/
      - ./docs/:/home/docs/
      - ./extensions/:/home/extensions/
      - ./api/transcription_svc/:/home/transcription/
      - ./dashboard/:/home/dashboard/
      # Exclude mount node_modules directory
      #- /usr/src/app/node_modules/

  # web:
  #   build: ./web/
  #   ports:
  #   - "8000:8000"
  #   volumes:
  #     - ./web/:/home/web/
